# -*- coding: utf-8 -*-
"""OpenAiTweetSentimentAnalaysisDemo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UNhH-xySNyps85O7-Ux8u7ZIWE6RTgKE
"""

!pip install openai

!pip3 install twint

!pip install nest-asyncio

import nest_asyncio
nest_asyncio.apply()

import twint

# Set up TWINT config
c = twint.Config()
c.Search = "football"
# Custom output format
c.Limit = 50
c.Since='2022-12-09'
c.Pandas = True
twint.run.Search(c)

def column_names():
    return twint.output.panda.Tweets_df.columns
def twint_to_pd(columns):
    return twint.output.panda.Tweets_df[columns]
column_names()

tweet_df = twint_to_pd(["date", "username", "tweet", "hashtags"])
tweet_df.head(10)

print(len(tweet_df))

tweet_list = tweet_df['tweet'].tolist()

import json
#Store you OpenAPI key in a json file
OPENAI_API_KEY = ''
with open('/content/OpenAI.json', 'r') as file_to_read:
    json_data = json.load(file_to_read)
    OPENAI_API_KEY = json_data["OPENAI_API_KEY"]

import os
import openai

openai.api_key =  OPENAI_API_KEY

response = openai.Completion.create(
  model="text-davinci-003",
  prompt="Classify the sentiment in these tweets:\n\n1. \"I can't stand homework\"\n2. \"This sucks. I'm bored 😠\"\n3. \"I can't wait for Halloween!!!\"\n4. \"My cat is adorable ❤️❤️\"\n5. \"I hate chocolate\"\n\nTweet sentiment ratings:",
  temperature=0,
  max_tokens=60,
  top_p=1.0,
  frequency_penalty=0.0,
  presence_penalty=0.0
)

print(response)

i =1
tweet_str=''
for tweet in tweet_list:
   tweet_str = tweet_str + str(i) +'.'+'"'+tweet+'"'+'\n'
   i=i+1
   if i ==10:
     break

tweet_str

prompt="Classify the sentiment in these tweets:\n" + tweet_str + "\n Tweet sentiment ratings:"

prompt

response = openai.Completion.create(
  model="text-davinci-003",
  prompt= prompt,
  temperature=0,
  max_tokens=120,
  top_p=1.0,
  frequency_penalty=0.0,
  presence_penalty=0.0
)

response

tweet_str.split('\n')

(response["choices"][0]["text"]).split('\n')

